export const LEAD_STATUSES = [
  'NEW',
  'CONTACTED',
  'INTERESTED',
  'FOLLOWUP',
  'DOCUMENT_PENDING',
  'CONFIRMED',
  'LOST',
];

export const LEAD_SOURCES = [
  'Website',
  'Instagram Ads',
  'Facebook Ads',
  'Google Ads',
  'YouTube',
  'Manual Entry',
  'Walk-in',
  'Referral',
];

export const COUNSELORS = [
  'Jane Doe',
  'John Smith',
  'Alice Williams',
  'Bob Johnson',
];

export const mockLeads = [
  {
    id: 'L-1001',
    fullName: 'Rahul Sharma',
    phone: '+91 98765 43210',
    email: 'rahul.s@example.com',
    parentPhone: '+91 98765 43211',
    courseInterested: 'B.Tech Computer Science',
    city: 'Mumbai',
    state: 'Maharashtra',
    source: 'Website',
    status: 'NEW',
    assignedCounselor: 'Jane Doe',
    notes: 'Interested in AI specialisation.',
    createdDate: '2026-05-10T10:00:00Z',
  },
  {
    id: 'L-1002',
    fullName: 'Priya Patel',
    phone: '+91 87654 32109',
    email: 'priya.p@example.com',
    parentPhone: '+91 87654 32110',
    courseInterested: 'MBA Marketing',
    city: 'Ahmedabad',
    state: 'Gujarat',
    source: 'Instagram Ads',
    status: 'CONTACTED',
    assignedCounselor: 'John Smith',
    notes: 'Called on 12th, asked to call back in evening.',
    createdDate: '2026-05-12T14:30:00Z',
  },
  {
    id: 'L-1003',
    fullName: 'Amit Kumar',
    phone: '+91 76543 21098',
    email: 'amit.k@example.com',
    parentPhone: '+91 76543 21100',
    courseInterested: 'B.Com Honours',
    city: 'Delhi',
    state: 'Delhi',
    source: 'Facebook Ads',
    status: 'FOLLOWUP',
    assignedCounselor: 'Alice Williams',
    notes: 'Need scholarship details.',
    createdDate: '2026-05-13T09:15:00Z',
  },
  {
    id: 'L-1004',
    fullName: 'Sneha Reddy',
    phone: '+91 65432 10987',
    email: 'sneha.r@example.com',
    parentPhone: '+91 65432 11000',
    courseInterested: 'B.Arch',
    city: 'Hyderabad',
    state: 'Telangana',
    source: 'Referral',
    status: 'CONFIRMED',
    assignedCounselor: 'Bob Johnson',
    notes: 'Admission fee paid.',
    createdDate: '2026-05-08T11:45:00Z',
  },
  {
    id: 'L-1005',
    fullName: 'Vikram Singh',
    phone: '+91 54321 09876',
    email: 'vikram.s@example.com',
    parentPhone: '+91 54321 10000',
    courseInterested: 'B.Tech Mechanical',
    city: 'Jaipur',
    state: 'Rajasthan',
    source: 'Google Ads',
    status: 'LOST',
    assignedCounselor: 'Jane Doe',
    notes: 'Joined another college.',
    createdDate: '2026-05-05T16:20:00Z',
  },
  {
    id: 'L-1006',
    fullName: 'Ananya Iyer',
    phone: '+91 91234 56789',
    email: 'ananya.i@example.com',
    parentPhone: '+91 91234 56780',
    courseInterested: 'B.Sc Physics',
    city: 'Chennai',
    state: 'Tamil Nadu',
    source: 'YouTube',
    status: 'INTERESTED',
    assignedCounselor: 'Alice Williams',
    notes: 'Brilliant student, looking for research opportunities.',
    createdDate: '2026-05-14T11:00:00Z',
  },
  {
    id: 'L-1007',
    fullName: 'Karan Mehra',
    phone: '+91 92345 67890',
    email: 'karan.m@example.com',
    parentPhone: '+91 92345 67891',
    courseInterested: 'BBA',
    city: 'Pune',
    state: 'Maharashtra',
    source: 'Walk-in',
    status: 'NEW',
    assignedCounselor: 'John Smith',
    notes: 'Visited with parents. Looks promising.',
    createdDate: '2026-05-15T10:30:00Z',
  },
  {
    id: 'L-1008',
    fullName: 'Sonia Gupta',
    phone: '+91 93456 78901',
    email: 'sonia.g@example.com',
    parentPhone: '+91 93456 78902',
    courseInterested: 'M.Tech AI',
    city: 'Bangalore',
    state: 'Karnataka',
    source: 'Manual Entry',
    status: 'DOCUMENT_PENDING',
    assignedCounselor: 'Jane Doe',
    notes: 'Awaiting graduation marksheet.',
    createdDate: '2026-05-01T09:00:00Z',
  },
  {
    id: 'L-1009',
    fullName: 'Rohan Verma',
    phone: '+91 94567 89012',
    email: 'rohan.v@example.com',
    parentPhone: '+91 94567 89013',
    courseInterested: 'B.Tech IT',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    source: 'Website',
    status: 'CONTACTED',
    assignedCounselor: 'Bob Johnson',
    notes: 'Enquired about placement statistics.',
    createdDate: '2026-05-14T15:45:00Z',
  },
  {
    id: 'L-1010',
    fullName: 'Megha Rao',
    phone: '+91 95678 90123',
    email: 'megha.r@example.com',
    parentPhone: '+91 95678 90124',
    courseInterested: 'B.Com CA',
    city: 'Mysore',
    state: 'Karnataka',
    source: 'Facebook Ads',
    status: 'INTERESTED',
    assignedCounselor: 'Alice Williams',
    notes: 'Wants to know about hostel facilities.',
    createdDate: '2026-05-13T12:00:00Z',
  },
  {
    id: 'L-1011',
    fullName: 'Akash Das',
    phone: '+91 96789 01234',
    email: 'akash.d@example.com',
    parentPhone: '+91 96789 01235',
    courseInterested: 'B.Tech Civil',
    city: 'Kolkata',
    state: 'West Bengal',
    source: 'Google Ads',
    status: 'FOLLOWUP',
    assignedCounselor: 'John Smith',
    notes: 'Call scheduled for next Monday.',
    createdDate: '2026-05-12T16:30:00Z',
  },
  {
    id: 'L-1012',
    fullName: 'Ishani Roy',
    phone: '+91 97890 12345',
    email: 'ishani.r@example.com',
    parentPhone: '+91 97890 12346',
    courseInterested: 'BA English',
    city: 'Guwahati',
    state: 'Assam',
    source: 'Instagram Ads',
    status: 'NEW',
    assignedCounselor: 'Jane Doe',
    notes: 'Interested in creative writing elective.',
    createdDate: '2026-05-15T08:15:00Z',
  }
];

export const mockStats = [
  { title: 'Total Leads', value: '1,284', trend: 12, color: 'primary' },
  { title: 'Conversions', value: '452', trend: 8, color: 'success' },
  { title: 'Pending Followups', value: '86', trend: -4, color: 'warning' },
  { title: 'Lost Leads', value: '124', trend: 2, color: 'danger' },
];

export const mockActivity = [
  { id: 1, user: 'Jane Doe', action: 'Added Lead', target: 'Rahul Sharma', time: '2 hours ago', status: 'NEW' },
  { id: 2, user: 'John Smith', action: 'Updated Status', target: 'Priya Patel', time: '4 hours ago', status: 'CONTACTED' },
  { id: 3, user: 'Alice Williams', action: 'Added Note', target: 'Amit Kumar', time: 'Yesterday', status: 'FOLLOWUP' },
  { id: 4, user: 'Bob Johnson', action: 'Confirmed Admission', target: 'Sneha Reddy', time: '2 days ago', status: 'CONFIRMED' },
];

export const mockFollowups = [
  { id: 1, leadName: 'Amit Kumar', time: '10:30 AM', date: '2026-05-16', type: 'Call', priority: 'High' },
  { id: 2, leadName: 'Akash Das', time: '02:00 PM', date: '2026-05-16', type: 'Email', priority: 'Medium' },
  { id: 3, leadName: 'Rohan Verma', time: '11:00 AM', date: '2026-05-17', type: 'Visit', priority: 'High' },
];
